config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_em_all'  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# Company
# - Id ["1", "2"]
# - Code ["1010002", "0999"]
# - Name ["Imperial", "Eclipse"]

class Company < ApplicationRecord    
    has_many :cost_centers, dependent: :destroy
    has_many :users, through: :cost_centers, dependent: :nullify

    validates :code, presence: true
    validates :name, presence: true    
end

app/models/cost_center.rb
# Cost Center
# - Id ["1", "2"]
# - Code ["001", "002"]
# - Company Id ["1", "1"]
# - Name ["Total", "Total"]
# - Location ["PE", "Pretoria"]
# - Departments [["1", "3"], ["1"]]

class CostCenter < ApplicationRecord
    belongs_to :company
    has_many :departments, dependent: :nullify
    has_many :users, dependent: :nullify

    validates :code, presence: true
    validates :company, presence: true
    validates :name, presence: true
end

app/models/department.rb
# Department
# - Id ["1", "3"]
# - Code ["001", "003"]
# - Name ["Finance", "HR"]

class Deparment < ApplicationRecord    
    belongs_to :cost_center

    validates :code, presence: true
    validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/task.rb
# # Task
# # - Id
# # - Code ["005"]
# # - Customer id ["1"]
# # - Requested by ["8"]
# # - Subject ["Help the user log in"]
# # - Description ["Help the user log in with something"]
# # - Type ["1"]
# # - Department ["3"]
# # - Status ["1"]
# # - Responsible ["0999"]
# # - Assignee ["11"]
# # - Item
# # - Started at
# # - Completed at

 class Task < ApplicationRecord    
    belongs_to :customer, class_name: 'Company' 
    belongs_to :assignee, class_name: 'User' 
    belongs_to :requested_by, class_name: 'User' 
    belongs_to :responsible, class_name: 'User'
    belongs_to :status, class_name: 'TaskStatus' 
    belongs_to :type, class_name: 'TaskType' 
    
    validates :code, presence: true 
    validates :customer, presence: true   
    validates :assignee, presence: true 
    validates :requested_by, presence: true   
    validates :responsible, presence: true 
    validates :status, presence: true
    validates :type, presence: true 
    validates :subject, presence: true 
    validates :description, presence: true 
    validates :started_at, presence: true     
    validates :completed_at, presence: true                                 
 end

app/models/task_status.rb
class TaskStatus < ApplicationRecord    
    validates :code, presence: true
    validates :title, presence: true    
end



# TaskStatus
# - Id ["1", "2"]
# - Code ["01", "02"]
# - Title ["New", "In progress"]

app/models/task_type.rb
class TaskType < ApplicationRecord    
    validates :code, presence: true
    validates :title, presence: true    
end

#  TaskType
# - Id ["1", "2", "3"]
# - Code ["001", "002", "003"]
# - Title ["Support", "Finance", "Assets"]

app/models/user.rb
# User
# - Id ["8", "11"]
# - Code ["001", "002"]
# - Company id ["1010002", "0999"]
# - Cost Center id ["1", "2"]
# - First name ["Susan", "Bryan"]
# - Last name

class User < ApplicationRecord
    belongs_to :company
    belongs_to :cost_center

    validates :code, presence: true
    validates :company, presence: true
    validates :cost_center, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def trash_em
        @trash_em = List.where(:completed => true).destroy_all
        redirect_to lists_url, notice: 'All Marked Items Where Successfully Deleted.'
    end

    def trash_em_all
        @trash_em_all = List.all.destroy_all
        redirect_to lists_url, notice: 'All Items Where Successfully Deleted.'
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
  </head>

  <body>

  <%= render 'lists/navbar' %>

    <div class="container">
      <br/>
      <%= render 'flash' %> 
      
      <%= yield %>

    </div>    
    
  </body>

</html>

app/views/lists/_flash.html.erb
<br/>

<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">            
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>    

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %>    
  </div>

  <div class="actions">
    <%= form.submit "Update Todo Item", class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <%= form.text_field :description, class: "form-control mr-sm-2" %>

    <%= form.submit "Add Todo Item", class: 'btn btn-outline-success my-2 my-sm-0' %>
  </div>
<% end %>
  

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-secondary bg-secondary">
<%= link_to "Task List", root_path, class: 'text-white' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Assigned To:
        </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Bryan Peens</a>
        <a class="dropdown-item" href="#">Michelle</a>
        <a class="dropdown-item" href="#">Whesley</a>
      </div>
      </li>
    
    </ul>
    <%= render 'form_index', list: @list %> 
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing Todo Item</h1>
<br/>
<div class="card" style="width: 18rem;">

  <div class="card-body">
    <%= render 'form', list: @list %> 
  </div>

</div>
<br/>
<br/>

<% link_to 'Show', @list %>
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<table class="table table-bordered">

  <tbody>
    <% @lists.each do |list| %>

      <% if list.completed %>
        <tr class="table-secondary">
          <td class="striker"><%= link_to list.description, edit_list_path(list) %><% list.description %></td>
          <td>
            <%= form_with(model: list, local: true) do |form| %>
              <%= form.text_field :description, type: 'hidden' %>
              <%= form.check_box :completed, :checked => false, :style => 'visibility: hidden' %> 
              <%= form.submit "Uncomplete Task", class: 'btn btn-outline-secondary btn-sm' %>
            <% end %>  
          </td>          
          <td>
            <% link_to 'Show', list %>
            <% link_to 'Edit', edit_list_path(list) %>
            <center><%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?'} %></center>
          </td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to list.description, edit_list_path(list) %><% list.description %></td>
          <td>
            <%= form_with(model: list, local: true) do |form| %>
              <%= form.text_field :description, type: 'hidden' %>
              <%= form.check_box :completed, :checked => true, :style => 'visibility: hidden' %> 
              <%= form.submit "Complete Task", class: 'btn btn-outline-primary btn-sm' %>
            <% end %>  
          </td>
          <td>
            <% link_to 'Show', list %>
            <% link_to 'Edit', edit_list_path(list) %>
            <center><%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?'} %></center>
          </td>
        </tr>      
      <% end %>
    <% end %>
  </tbody>
</table>
<% link_to 'New Todo Item', new_list_path, class: 'btn btn-success' %>
<br/>
<br/>
<%= link_to 'Delete Marked Items', home_trash_em_path, class: 'btn btn-outline-warning', data: { confirm: 'Are you sure?'}  %>
<%= link_to 'Delete All Items', home_trash_em_all_path, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?'}  %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Todo Item Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>